/** Vendored from Figma node 7149:8731 — local copies so MCP asset URLs never break the landing page. */
const b = `${import.meta.env.BASE_URL.replace(/\/$/, '')}/llumen-assets/landing`

export const landingAssets = {
  users: `${b}/users.png`,
  eyeSlash: `${b}/eye-slash.png`,
  squaresFour: `${b}/squares-four.png`,
  plus: `${b}/plus.png`,
  plusLarge: `${b}/plus-large.png`,
  signOut: `${b}/sign-out.png`,
  question: `${b}/question.png`,
  gear: `${b}/gear.png`,
  user: `${b}/user.png`,
  userBtn: `${b}/user-btn.png`,
  caretDown: `${b}/caret-down.png`,
  createBriefingCta: `${b}/create-briefing-cta.png`,
  createBriefingCta1: `${b}/create-briefing-cta-1.png`,
  createBriefingCta2: `${b}/create-briefing-cta-2.png`,
  featuredMap: `${b}/frame-featured-map.png`,
  image115: `${b}/image-115.png`,
  image116: `${b}/image-116.png`,
  image117: `${b}/image-117.png`,
  image118: `${b}/image-118.png`,
  image119: `${b}/image-119.png`,
  image120: `${b}/image-120.png`,
  image121: `${b}/image-121.png`,
  vectorOps: `${b}/vector-ops.png`,
  vectorIt: `${b}/vector-it.png`,
  dotsThree: `${b}/dots-three.png`,
  dotsThree1: `${b}/dots-three-1.png`,
  starFour: `${b}/star-four.png`,
  play: `${b}/play.png`,
  magnifyingGlass: `${b}/magnifying-glass.png`,
  bell: `${b}/bell.png`,
  separator: `${b}/separator.png`,
  frameSwitcher: `${b}/frame-switcher.png`,
} as const
